title: Data Catalog Interoperability Protocol
github: http://github.com/dataprotocols/data-catalog-spec
twitter: OKFNLabs
mailinglist: http://lists.okfn.org/mailman/listinfo/data-catalogs
googleanalytics: UA-8271754-41
